### ISSUE TITLE
Edit examples to match command

### ISSUE THREAD

**Issue by jpeak5** [lsulibraries/islandora_elide_download#1]
Running `drush islandora-elide-download -h` should give the user the information they need to run the command successfully.

Currently, there are at least two discrepancies between the command documentation (`-h`) and the command definition:

1. Swap underscores for hyphens in the command name to match the actually command
2. `--op=active` needs to be just `elide` or `enable` with no op at all...

@flummingbird

**Comment by flummingbird** [comment]
I've made the requested changes. -h should give command with dashes not underscores, and the option can just be elide or enable, and is shown as such in the command example.
4df31d950bfa9a9f0bf9e1dafbe449a00bdcaef3
